name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-24.04]
        python-version: ["3.13"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "**/pyproject.toml"

    - name: Build pybmds
      shell: bash
      run: |

        # create virtual environment
        uv venv --python=${{ matrix.python-version }}

        case "$RUNNER_OS" in
            Linux)
            source .venv/bin/activate
            export CMAKE_PREFIX_PATH=${{ github.workspace }}/.venv/lib/python${{ matrix.python-version }}/site-packages/pybind11/share/cmake
            export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
            ;;
            Windows)
            source .venv/Scripts/activate
            ;;
            macOS)
            source .venv/bin/activate
            ;;
        esac

        # install some dependencies
        uv pip install pybind11 setuptools

        # compile program
        uv pip install -v -e .

        py.test
