name: Build package wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        # os: [ubuntu-24.04, windows-2022, macos-14]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v3.1.3
      env:
        CIBW_BUILD="cp313*"
        CIBW_BEFORE_ALL_LINUX="source tools/cibw_linux_before_all.sh"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl
