name: Build package wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-24.04, windows-2022, macos-14]
        os: [windows-2022]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v3.1.3
      env:
        CIBW_BUILD: "cp313*"
        CIBW_SKIP: "*musllinux*"

        CIBW_BEFORE_ALL_WINDOWS: . .\tools\cibw_before_windows.ps1
        CIBW_ENVIRONMENT_WINDOWS: CMAKE_PREFIX_PATH=${{ github.workspace }}\pybind11\pybind11\share\cmake

        CIBW_BEFORE_ALL_LINUX: "source tools/cibw_before_linux.sh"
        CIBW_ENVIRONMENT_LINUX: "CMAKE_PREFIX_PATH=/project/pybind11/pybind11/share/cmake"

        CIBW_BEFORE_ALL_MACOS: "source tools/cibw_before_linux.sh"
        CIBW_ENVIRONMENT_MACOS: "CMAKE_PREFIX_PATH=${{ github.workspace }}/pybind11/pybind11/share/cmake"
        MACOSX_DEPLOYMENT_TARGET: "14.0"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl
